
services:
  app:
    image: taskdelat-app
    container_name: taskdelat-app
    ports:
      - "8085:8085"
    environment:
      PGHOST: host.docker.internal
      PGPORT: 5433
      PGDATABASE: taskdelat
      PGUSER: postgres
      PGPASSWORD: tvoipassword

      SPRING_DATASOURCE_URL: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
      SPRING_DATASOURCE_USERNAME: ${PGUSER}
      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}

    restart: always

